version: "3"

services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    tty: true
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    restart: on-failure
    env_file:
      - .env
    command: sh -c "celery -A config worker -l INFO"
    depends_on:
      - redis
      - db
      - api

  celery-beat:
    build: .
    tty: true
    restart: on-failure
    env_file:
      - .env
    command: sh -c "celery -A config beat -l INFO"
    depends_on:
      - redis
      - db
      - api

volumes:
  pg_data: