# Generated by Django 5.0.6 on 2024-06-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение за выполнение')),
                ('frequency', models.CharField(choices=[('EVERY_DAY', 'раз в день'), ('EVERY OTHER DAY', 'через день'), ('EVERY WEEK', 'раз в неделю')], default='EVERY_DAY', max_length=100, verbose_name='Периодичность')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
                'ordering': ('pleasant_habit',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('duration', models.PositiveIntegerField(default=120, verbose_name='Время на выполнение (сек)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности привычки')),
                ('is_pleasant_habit', models.BooleanField(default=True, verbose_name='Признак приятности привычки')),
            ],
            options={
                'verbose_name': 'Добавить привычку',
                'verbose_name_plural': 'Настройка привычки',
            },
        ),
    ]
